'use client'

import { useState } from 'react'
import type { FormEvent } from 'react'
import { supabase } from '../../../lib/supabase'

export default function LeadForm({ propertyId, projectName }: { propertyId: string; projectName: string }) {
  const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [lineId,setLineId]=useState(''); const [budget,setBudget]=useState(''); const [moveInDate,setMoveInDate]=useState(''); const [note,setNote]=useState(''); const [loading,setLoading]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('')
  async function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault(); setLoading(true); setMessage(''); setError(''); const {error}=await supabase.from('leads').insert({customer_name:name.trim(),phone:phone.trim()||null,line_id:lineId.trim()||null,budget_max:budget?Number(budget):null,move_in_date:moveInDate||null,interested_property_id:propertyId,note:note.trim()||`สนใจโครงการ ${projectName}`,status:'new'}); if(error){setError(`ส่งข้อมูลไม่สำเร็จ: ${error.message}`);setLoading(false);return} setMessage('ได้รับข้อมูลแล้ว ข้าวจะติดต่อกลับโดยเร็วค่ะ'); setName('');setPhone('');setLineId('');setBudget('');setMoveInDate('');setNote('');setLoading(false) }
  return <div className="hotel-enquiry-form"><div className="hotel-kicker dark">REQUEST A PRIVATE VIEWING</div><h2>นัดชมแบบส่วนตัว</h2><p>Leave your details and we will arrange the next step personally.</p>{message&&<div className="kj-message">{message}</div>}{error&&<div className="kj-message kj-message-error">{error}</div>}<form onSubmit={submit}><label><span>NAME · ชื่อ *</span><input required value={name} onChange={e=>setName(e.target.value)} /></label><label><span>PHONE · เบอร์โทร *</span><input required value={phone} onChange={e=>setPhone(e.target.value)} /></label><label><span>LINE ID</span><input value={lineId} onChange={e=>setLineId(e.target.value)} /></label><div className="hotel-form-2"><label><span>BUDGET / MONTH</span><input type="number" value={budget} onChange={e=>setBudget(e.target.value)} /></label><label><span>MOVE-IN DATE</span><input type="date" value={moveInDate} onChange={e=>setMoveInDate(e.target.value)} /></label></div><label><span>MESSAGE · รายละเอียดเพิ่มเติม</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Preferred viewing time, pets, special requirements..." /></label><button disabled={loading} className="hotel-button dark">{loading?'Sending...':'Send Private Enquiry'}</button></form></div>
}
